project:
  name: quickstart-aws-vpc
  owner: quickstart@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - cn-north-1
  - cn-northwest-1
  s3_bucket: ''
tests:
  2az-cn-north-1:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      CreateAdditionalPrivateSubnets: 'false'
      CreatePrivateSubnets: 'true'
      NumberOfAZs: '2'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - cn-north-1
    s3_bucket: ''
    template: templates/aws-vpc.template
  3az-cn-northwest-1:
    parameters:
      AvailabilityZones: $[taskcat_getaz_3]
      CreateAdditionalPrivateSubnets: 'false'
      CreatePrivateSubnets: 'true'
      NumberOfAZs: '3'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - cn-northwest-1
    s3_bucket: ''
    template: templates/aws-vpc.template
  3az-complete-us-east-2:
    parameters:
      AvailabilityZones: $[taskcat_getaz_3]
      CreateAdditionalPrivateSubnets: 'true'
      CreatePrivateSubnets: 'true'
      NumberOfAZs: '3'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - us-east-2
    s3_bucket: ''
    template: templates/aws-vpc.template
  3az-eu-west-1:
    parameters:
      AvailabilityZones: $[taskcat_getaz_3]
      CreateAdditionalPrivateSubnets: 'false'
      CreatePrivateSubnets: 'true'
      NumberOfAZs: '3'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - eu-west-1
    s3_bucket: ''
    template: templates/aws-vpc.template
  3az-public-us-west-2:
    parameters:
      AvailabilityZones: $[taskcat_getaz_3]
      CreateAdditionalPrivateSubnets: 'false'
      CreatePrivateSubnets: 'false'
      NumberOfAZs: '3'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - us-west-2
    s3_bucket: ''
    template: templates/aws-vpc.template
  4az-complete-us-east-1:
    parameters:
      AvailabilityZones: $[taskcat_getaz_4]
      CreateAdditionalPrivateSubnets: 'true'
      CreatePrivateSubnets: 'true'
      NumberOfAZs: '4'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/aws-vpc.template
  4az-public-us-east-1:
    parameters:
      AvailabilityZones: $[taskcat_getaz_4]
      CreateAdditionalPrivateSubnets: 'false'
      CreatePrivateSubnets: 'false'
      NumberOfAZs: '4'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/aws-vpc.template
  4az-us-east-1:
    parameters:
      AvailabilityZones: $[taskcat_getaz_4]
      CreateAdditionalPrivateSubnets: 'false'
      CreatePrivateSubnets: 'true'
      NumberOfAZs: '4'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/aws-vpc.template
  dedicated-us-west-1:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      CreateAdditionalPrivateSubnets: 'false'
      CreatePrivateSubnets: 'false'
      NumberOfAZs: '2'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: dedicated
    regions:
    - us-west-1
    s3_bucket: ''
    template: templates/aws-vpc.template
  vpc-complete:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      CreateAdditionalPrivateSubnets: 'true'
      CreatePrivateSubnets: 'true'
      NumberOfAZs: '2'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - cn-north-1
    - cn-northwest-1
    s3_bucket: ''
    template: templates/aws-vpc.template
  vpc-defaults:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      CreateAdditionalPrivateSubnets: 'false'
      CreatePrivateSubnets: 'true'
      NumberOfAZs: '2'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - cn-north-1
    - cn-northwest-1
    s3_bucket: ''
    template: templates/aws-vpc.template
  vpc-defaults-sa-east-1:
    parameters:
      AvailabilityZones: sa-east-1b,sa-east-1c
      CreateAdditionalPrivateSubnets: 'false'
      CreatePrivateSubnets: 'true'
      NumberOfAZs: '2'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - sa-east-1
    s3_bucket: ''
    template: templates/aws-vpc.template
  vpc-public:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      CreateAdditionalPrivateSubnets: 'false'
      CreatePrivateSubnets: 'false'
      NumberOfAZs: '2'
      PrivateSubnet1ACIDR: 10.0.0.0/19
      PrivateSubnet1BCIDR: 10.0.192.0/21
      PrivateSubnet2ACIDR: 10.0.32.0/19
      PrivateSubnet2BCIDR: 10.0.200.0/21
      PrivateSubnet3ACIDR: 10.0.64.0/19
      PrivateSubnet3BCIDR: 10.0.208.0/21
      PrivateSubnet4ACIDR: 10.0.96.0/19
      PrivateSubnet4BCIDR: 10.0.216.0/21
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      PublicSubnet3CIDR: 10.0.160.0/20
      PublicSubnet4CIDR: 10.0.176.0/20
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
    regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - cn-north-1
    - cn-northwest-1
    s3_bucket: ''
    template: templates/aws-vpc.template
